@startuml
skinparam classAttributeIconSize 0
title Пример Онтологии by Иван Иванов
class set {
  Коллекция уникальных элементов' # Описание типа в онтологии
}
class bool {
  None
}
class element {
  Индивидуальный объект в множестве
}
class descartes <<Function>> {
  +descartes(set, set) : (s, e, t)
  Множество-результат
}
class isSetElem <<Function>> {
  +isSetElem(element, который, set) : (b, o, o, l)
  None
}
note "multiset subclass set" as N3627
@enduml