@startuml
skinparam classAttributeIconSize 0
title Пример Онтологии by Иван Иванов
class set {
  Коллекция уникальных элементов
}
class bool {
  true или false
}
class element {
  Индивидуальный объект в множестве
}
class descartes <<Function>> {
  +descartes(set, set) : (set)
  Декартово произведение
}
class isSetElem <<Function>> {
  +isSetElem(element) : (bool)
  Проверка принадлежности
}
note "multiset subclass set" as N9397
@enduml